### ISSUE TITLE
how to get tab click ?

### ISSUE THREAD

**Issue by birjubhatt** [ATHBK/UltimateTabLayout#11]
i have only two tab 1st is form data and second is address data 
i want do ...until 1st page (tab) validation not complete user can not go second tab 

there for user click second tab i need to check first page data is filled then user can go second page...

so i need tab click....using your library how can i manage this condition ????

how to find which tab is clicked and perform stuff before fragment changed ?

**Comment by ATHBK** [comment]
Hi bro, I update for this in new version. 
```
        tabLayout.setOnClickTabListener(new OnClickTabListener() {
            @Override
            public void onClickTab(int currentPos) {
                Log.e("LOG", "OnClickTab " + currentPos);
                    viewPager.setCurrentItem(currentPos);
            }
        });
        tabLayout.setViewPager(viewPager, adapter);
```
