### ISSUE TITLE
set tab's titles only image 

### ISSUE THREAD

**Issue by ismailtosun** [ATHBK/UltimateTabLayout#2]
is it possible to tab tittles only image ?

**Comment by ATHBK** [comment]
Hey bro, you can do it. 
Your adapter must implement class IFTabAdapter.
```
 @Override
    public String getTitle(int position) {
       //if return null or return "", you will show only images.
        return "TAB " + position;
    }
```

**Comment by NayanaRBhoj** [comment]
How to set Tab with TextVIew and ImageView, with selected and deselected different images and text color change???
