### ISSUE TITLE
SetTypeface to Titles

### ISSUE THREAD

**Issue by mosi5505** [ATHBK/UltimateTabLayout#3]
Hi Dear...
with the thanks for your library... i want to set Type face for titles... please update library... thanks...
or learn me how to use this feature...

best regards.
Mostafa

**Comment by ATHBK** [comment]
Hey bro. I updated version 1.2.4 for this issues.
This is new attrs's 👍 
```
app:tab_resource_font="font/Roboto-BoldItalic.ttf"
```
You can use in xml. You can see my sample for use your project.

**Comment by mosi5505** [comment]
Hi dear tnx for your good library and your attention...
in your library if i choose sliding, font is wrong and if i choose fixed its work correct...
plz help me...
best tnx
