### ISSUE TITLE
app:tab_resource_font in tab_style=sliding

### ISSUE THREAD

**Issue by mosi5505** [ATHBK/UltimateTabLayout#4]
Hi dear tnx for your good library and your attention...
in your library if i choose sliding, font is wrong and if i choose fixed its work correct...
plz help me...
best tnx

**Comment by ATHBK** [comment]
Hey bro, I fixed this issues in new version 1.2.5
Please follow 👍 
``
compile 'com.github.ATHBK:UltimateTabLayout:1.2.5'
``
