### ISSUE TITLE
Tab Width for sliding mode

### ISSUE THREAD

**Issue by uzman** [ATHBK/UltimateTabLayout#7]
Hi,
is it possible to make tab width dynamic for app:tab_style="sliding" ?

thanks...

**Comment by birjubhatt** [comment]
hi ..i also want use this feature in my app ..i have multiple fragments

**Comment by ATHBK** [comment]
Hi everyone, you can set property tab_width for change to tab in style's sliding.
```
  app:tab_width="100dp"
```
